/* Small functional destination demos, entered through landmarks in the village. */
(() => {
'use strict';
const $=s=>document.querySelector(s),params=new URLSearchParams(location.search),place=params.get('place')==='library'?'library':'military',village=params.get('village')==='daghan'?'daghan':'gktc';
const node=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
const say=t=>$('#announcement').textContent=t;
const tasks=[{title:'Prepare the weekly news digest',agent:'Gazeteci',status:'In progress'},{title:'Review Acme Enerji prospect',agent:'Girard',status:'Needs approval'},{title:'Create the next campaign visual',agent:'Kandinsky',status:'Planned'}];
const initialTasks=tasks.map(x=>({...x}));let runs=[{title:'Morning village briefing',detail:'Today, 08:00 · 8 agents · 4 steps',status:'Completed'},{title:'Weekly research digest',detail:'Today, 09:15 · Gazeteci · gathering sources',status:'Running'}];
const documents=[{title:'The weekly field report',type:'Research · Gazeteci',date:'Today',body:'Six sample sources were collected for this week’s village briefing.\n\nEnergy: new capacity announcements are ready for verification.\nTechnology: three developments are shortlisted for the digest.\nNext step: review the source notes at the GGI post office.'},{title:'Acme Enerji · prospect notes',type:'Prospect · Girard',date:'Yesterday',body:'Plant capacity under review: 1,200 kWp.\n\nThe previous record lists 800 kWp. This mock document illustrates the review context; it does not update a real record.\n\nOwner: Girard. Decision: awaiting approval.'},{title:'Village design principles',type:'Guide · Text Writer',date:'2 days ago',body:'The office is a world.\n\nAgents belong to environments, not desks. Each district expresses its work through architecture, props and animation.\n\nPlaces act as navigation. Always offer a clear route back to the village and preserve the camera position.'},{title:'September creative direction',type:'Design · Kandinsky',date:'3 days ago',body:'Warm stone, quiet greens, terracotta roofs and carefully placed gold.\n\nBuild a lived-in pixel world: couriers, papers, gardens, water and small gestures. Make animations meaningful and keep a pause control available.'}];
const tabs=place==='library'?['Documents','KPIs']:['Tasks','Workflows','Runs'];let active=tabs.find(x=>x.toLowerCase()===params.get('tab'))||tabs[0];
$('#page-title').textContent=place==='library'?'The Grand Library':'Command Grounds';document.title='Brownie · '+$('#page-title').textContent;$('#page-kicker').textContent=(village==='gktc'?'GKTC’S VILLAGE':'DAGHAN’S VILLAGE')+' / CIVIC GROUNDS';$('#page-description').textContent=place==='library'?'Keep knowledge close. Read the archive and understand the village’s progress.':'Turn ideas into work. Plan assignments, trace workflows and follow each run.';$('#page-emblem').textContent=place==='library'?'▤':'⚑';
function renderTabs(){const host=$('#page-tabs');host.replaceChildren();tabs.forEach((title,i)=>{const b=node('button','',title);b.id='tab-'+title.toLowerCase();b.setAttribute('role','tab');b.setAttribute('aria-selected',String(active===title));b.setAttribute('aria-controls','page-content');b.tabIndex=active===title?0:-1;b.onclick=()=>{active=title;renderTabs();render();$('#'+b.id).focus();const url=new URL(location.href);url.searchParams.set('tab',title.toLowerCase());history.replaceState(null,'',url);};b.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const index=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;$('#tab-'+tabs[index].toLowerCase()).click();};host.append(b);});$('#page-content').setAttribute('aria-labelledby','tab-'+active.toLowerCase());}
function heading(text,action){const bar=node('div','section-bar');bar.append(node('h2','',text));if(action)bar.append(action);return bar;}
function row(title,detail,status){const r=node('div','page-row'),t=node('div','row-text');t.append(node('strong','',title),node('small','',detail));r.append(t,node('span','pill',status));return r;}
function render(){const host=$('#page-content');host.replaceChildren();if(active==='Tasks'){host.append(heading('Assignments'));const form=node('form','task-form'),input=node('input'),add=node('button','button primary','Add task');input.placeholder='A new task for the village…';input.setAttribute('aria-label','Task title');input.maxLength=120;add.type='submit';add.disabled=true;input.oninput=()=>add.disabled=!input.value.trim();form.append(input,add);form.onsubmit=e=>{e.preventDefault();const title=input.value.trim();if(!title)return;tasks.push({title,agent:'Unassigned',status:'Planned'});render();say('Task added locally.');};host.append(form);tasks.forEach((task,index)=>{const r=row(task.title,task.agent+' · sample assignment',task.status);if(task.status!=='Done'){const done=node('button','button small','Mark done');done.onclick=()=>{tasks[index].status='Done';render();say(task.title+' marked done locally.');};r.append(done);}host.append(r);});}
 else if(active==='Workflows'){host.append(heading('Weekly research digest'));host.append(node('p','subtle','A sample workflow connecting the newsroom, library and the GGI post office & court.'));const flow=node('div','workflow-line');['Gather sources','Draft the digest','Review & approve','Archive'].forEach((step,i)=>{if(i)flow.append(node('span','','→'));flow.append(node('div','workflow-step',(i+1)+'. '+step));});host.append(flow);const run=node('button','button primary','Simulate a run');run.onclick=()=>{runs.unshift({title:'Weekly research digest',detail:'Just now · local simulation · 4 sample steps',status:'Completed'});run.textContent='✓ Simulation complete';run.disabled=true;const notice=node('p','notice','Gather → Draft → Review → Archive completed as a local preview. See the sample entry under Runs. No agents were called.');host.append(notice);say('Workflow simulation completed locally.');};host.append(run);}
 else if(active==='Runs'){host.append(heading('Run history'),node('p','subtle','Sample activity and any workflow simulations you created on this page.'));runs.forEach(item=>host.append(row(item.title,item.detail,item.status)));}
 else if(active==='Documents'){host.append(heading('From the archive'));const label=node('label','search'),input=node('input');input.placeholder='Search the archive…';input.setAttribute('aria-label','Search documents');label.append(node('span','','⌕'),input);host.append(label);const list=node('div');host.append(list);function showDocs(){list.replaceChildren();const found=documents.filter(d=>(d.title+' '+d.type).toLowerCase().includes(input.value.toLowerCase()));found.forEach(doc=>{const r=row(doc.title,doc.type+' · '+doc.date,'Document');const read=node('button','button small','Read');read.onclick=()=>{$('#document-title').textContent=doc.title;$('#document-content').replaceChildren(...doc.body.split('\n\n').map(t=>node('p','',t)));$('#document-dialog').showModal();};r.append(read);list.append(r);});if(!found.length)list.append(node('p','notice','No matching documents. Try “village” or “report”.'));}input.oninput=showDocs;showDocs();}
 else{host.append(heading('A view of your progress'),node('p','subtle','Illustrative metrics for the selected village. These values are sample data.'));const grid=node('div','metric-grid');for(const [n,label] of [['24','tasks completed'],['8','reports archived'],['92%','successful runs']]){const m=node('div','metric');m.append(node('strong','',n),node('small','',label));grid.append(m);}host.append(grid,node('h2','','Work completed this week'));const bars=node('div','kpi-bars');bars.setAttribute('role','img');bars.setAttribute('aria-label','Sample daily tasks completed: Monday 2, Tuesday 4, Wednesday 3, Thursday 6, Friday 5, Saturday 4.');[35,65,48,100,83,66].forEach((h,i)=>{const bar=node('span');bar.style.height=h+'%';bar.title=['Monday: 2','Tuesday: 4','Wednesday: 3','Thursday: 6','Friday: 5','Saturday: 4'][i];bars.append(bar);});host.append(bars,node('p','demo-note','MON → SAT · SAMPLE COMPLETED TASKS'));}}
$('#document-close').onclick=()=>$('#document-dialog').close();$('#reset-page').onclick=()=>{tasks.splice(0,tasks.length,...initialTasks.map(x=>({...x})));runs=[{title:'Morning village briefing',detail:'Today, 08:00 · 8 agents · 4 steps',status:'Completed'},{title:'Weekly research digest',detail:'Today, 09:15 · Gazeteci · gathering sources',status:'Running'}];render();say('Page demo reset.');};renderTabs();render();
})();
